name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install self
        working-directory: ${{github.workspace}}
        run: |
          # Since pylate makes problems otherwise:
          pip3 install pylate --no-deps
          pip3 install .[test,dev]
          pip3 cache purge
      - name: Run tests
        working-directory: ${{github.workspace}}
        run: pytest --ignore-models tests
